version: "3.9"
services:
  web:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wp-admin
      - WORDPRESS_DB_PASSWORD=8569321A
      - WORDPRESS_DB_NAME=wp-database
  db:
    image: mysql
    expose:
      - 3306
      - 33060
    environment:
    - MYSQL_ROOT_PASSWORD=password1
    - MYSQL_USER=wp-admin
    - MYSQL_PASSWORD=8569321A
    - MYSQL_DATABASE=wp-database
    volumes:
    - data:/var/www/html
volumes:
 data:
      